---
services:
  db:
    container_name: db
    image: postgres:12
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./var/pgdata:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432

  backend:
    container_name: backend
    ### ========== for server ==========
    # image: backend-template:latest
    ### ========== for server ==========
    ### ========== for local development ==========
    build:
      context: ./project
    volumes:
      - ../backend.core:/usr/src/app
    command: npm run start:dev
    ### ========== for local development ==========
    env_file:
      - .env
    environment:
      NODE_ENV: ${NODE_ENV}
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:${POSTGRES_PORT}/${POSTGRES_DB}?schema=public
      BACKEND_PORT: ${BACKEND_PORT}
    ports:
      - ${BACKEND_PORT}:3000
    restart: unless-stopped
    depends_on:
      - db
